version: 0.2

env:
  variables:
    APP: "frontend"
    ACCOUNT: "812644853088"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
  build:
    commands:
      - docker build -t ${APP} -t ${APP}:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag ${APP}:$CODEBUILD_RESOLVED_SOURCE_VERSION ${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP}:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag ${APP}:latest ${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP}:latest
  post_build:
    commands:
      - docker push ${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP}:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push ${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP}:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' meteor ${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP}:$CODEBUILD_RESOLVED_SOURCE_VERSION > $CODEBUILD_SRC_DIR/imagedefinitions.json

artifacts:
  files: imagedefinitions.json
